"""Generates src data for engine method binds from extension_api.json.

One entry per engine class method: class, method, hash, return type and
argument types (as codes the C++ side understands, see api.h ArgType). This is
data, not code: one array, so it compiles in a moment however big the API is.
"""

import json
import sys

# Must match enum ArgType in src/api.h
CODES = {
    "void": "T_VOID", "bool": "T_BOOL", "int": "T_INT", "float": "T_FLOAT",
    "String": "T_STRING", "StringName": "T_STRING_NAME",
    "Vector2": "T_VECTOR2", "Vector2i": "T_VECTOR2I", "Vector3": "T_VECTOR3",
    "Vector3i": "T_VECTOR3I", "Rect2": "T_RECT2", "Color": "T_COLOR",
    "Variant": "T_VARIANT",
}


def code(type_name, is_object):
    if type_name.startswith("enum::") or type_name.startswith("bitfield::"):
        return "T_INT"
    if type_name in CODES:
        return CODES[type_name]
    if is_object:
        return "T_OBJECT"
    return "T_OTHER"


def main(api_path, out_path):
    api = json.load(open(api_path))
    classes = {c["name"] for c in api["classes"]}
    rows = []
    for cls in api["classes"]:
        for method in cls.get("methods", []):
            if method.get("is_virtual") or "hash" not in method:
                continue
            ret = method.get("return_value", {}).get("type", "void")
            args = [a["type"] for a in method.get("arguments", [])]
            flags = []
            if method.get("is_vararg"):
                flags.append("F_VARARG")
            if method.get("is_static"):
                flags.append("F_STATIC")
            if any(a.get("default_value") is not None for a in method.get("arguments", [])):
                flags.append("F_DEFAULTS")
            if len(args) > 8:
                flags.append("F_OTHER")  # more than the fast path handles
                args = args[:8]
            arg_codes = ", ".join(code(a, a in classes) for a in args) or "T_VOID"
            rows.append((cls["name"], method["name"], method["hash"], code(ret, ret in classes),
                         len(method.get("arguments", [])), arg_codes, " | ".join(flags) or "0"))
    rows.sort(key=lambda r: (r[0], r[1]))
    with open(out_path, "w") as out:
        out.write("// Generated by tools/gen_api_data.py; do not edit.\n")
        for r in rows:
            out.write(f'{{"{r[0]}", "{r[1]}", {r[2]}LL, {r[3]}, {r[4]}, {{{r[5]}}}, {r[6]}}},\n')


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
