"""Generates data tables from extension_api.json (data, not code: plain
arrays, so they compile in a moment however big the API is).

Writes, next to OUT (api_data.inc):
- api_data.inc: engine class methods: class, method, hash, return and argument
  type codes (see api.h ArgType), flags.
- utility_data.inc: utility functions (lerp, clampf, print…): name, hash,
  return and argument type codes, vararg flag.
- global_enum_data.inc: global enum values (KEY_SPACE, OK…) and their values.
- builtin_data.inc: members of builtin types (Vector2, Color…): constants,
  enum values and methods, flagging static ones.
- builtin_method_data.inc: builtin type methods with hash, and return and
  argument types as Variant type numbers (VARIANT_TYPE_ANY for Variant).
"""

import json
import os
import sys

# Must match enum ArgType in src/api.h
CODES = {
    "void": "T_VOID", "bool": "T_BOOL", "int": "T_INT", "float": "T_FLOAT",
    "String": "T_STRING", "StringName": "T_STRING_NAME",
    "Vector2": "T_VECTOR2", "Vector2i": "T_VECTOR2I", "Vector3": "T_VECTOR3",
    "Vector3i": "T_VECTOR3I", "Rect2": "T_RECT2", "Color": "T_COLOR",
    "Variant": "T_VARIANT", "NodePath": "T_NODE_PATH",
}


def code(type_name, is_object, ref_counted=False):
    if type_name.startswith("enum::") or type_name.startswith("bitfield::"):
        return "T_INT"
    if type_name in CODES:
        return CODES[type_name]
    if is_object:
        # Results of RefCounted classes (and plain Object, which may be one)
        # need reference handling: they keep the Variant route
        return "T_OBJECT_REF" if ref_counted or type_name == "Object" else "T_OBJECT"
    return "T_OTHER"


def main(api_path, out_path):
    api = json.load(open(api_path))
    classes = {c["name"] for c in api["classes"]}
    parents = {c["name"]: c.get("inherits", "") for c in api["classes"]}

    def is_ref_counted(name):
        while name:
            if name == "RefCounted":
                return True
            name = parents.get(name, "")
        return False
    rows = []
    for cls in api["classes"]:
        for method in cls.get("methods", []):
            if method.get("is_virtual") or "hash" not in method:
                continue
            ret = method.get("return_value", {}).get("type", "void")
            args = [a["type"] for a in method.get("arguments", [])]
            flags = []
            if method.get("is_vararg"):
                flags.append("F_VARARG")
            if method.get("is_static"):
                flags.append("F_STATIC")
            if any(a.get("default_value") is not None for a in method.get("arguments", [])):
                flags.append("F_DEFAULTS")
            if len(args) > 8:
                flags.append("F_OTHER")  # more than the fast path handles
                args = args[:8]
            arg_codes = ", ".join(code(a, a in classes, is_ref_counted(a)) for a in args) or "T_VOID"
            rows.append((cls["name"], method["name"], method["hash"], code(ret, ret in classes, is_ref_counted(ret)),
                         len(method.get("arguments", [])), arg_codes, " | ".join(flags) or "0"))
    rows.sort(key=lambda r: (r[0], r[1]))
    with open(out_path, "w") as out:
        out.write("// Generated by tools/gen_api_data.py; do not edit.\n")
        for r in rows:
            out.write(f'{{"{r[0]}", "{r[1]}", {r[2]}LL, {r[3]}, {r[4]}, {{{r[5]}}}, {r[6]}}},\n')

    out_dir = os.path.dirname(out_path)

    # Utility functions
    rows = []
    for u in api["utility_functions"]:
        ret = u.get("return_type", "void")
        args = [a["type"] for a in u.get("arguments", [])]
        arg_codes = ", ".join(code(a, a in classes, is_ref_counted(a)) for a in args[:8]) or "T_VOID"
        rows.append((u["name"], u["hash"], code(ret, ret in classes, is_ref_counted(ret)), len(args), arg_codes,
                     "true" if u.get("is_vararg") else "false"))
    rows.sort()
    with open(os.path.join(out_dir, "utility_data.inc"), "w") as out:
        out.write("// Generated by tools/gen_api_data.py; do not edit.\n")
        for r in rows:
            out.write(f'{{"{r[0]}", {r[1]}LL, {r[2]}, {r[3]}, {{{r[4]}}}, {r[5]}}},\n')

    # Global enum values
    rows = sorted((v["name"], v["value"]) for e in api["global_enums"] for v in e["values"])
    with open(os.path.join(out_dir, "global_enum_data.inc"), "w") as out:
        out.write("// Generated by tools/gen_api_data.py; do not edit.\n")
        for name, value in rows:
            out.write(f'{{"{name}", {value}LL}},\n')

    # Builtin type members: constants, enum values, methods
    rows = []
    for b in api["builtin_classes"]:
        for c in b.get("constants", []):
            rows.append((b["name"], c["name"], "B_CONSTANT", 0))
        for e in b.get("enums", []):
            for v in e["values"]:
                rows.append((b["name"], v["name"], "B_ENUM", v["value"]))
        for m in b.get("methods", []):
            rows.append((b["name"], m["name"], "B_STATIC" if m.get("is_static") else "B_METHOD", 0))
    rows.sort()
    builtin_rows = rows

    # Builtin methods with signatures, for direct method pointers
    type_ids = {v["name"]: v["value"] for e in api["global_enums"] if e["name"] == "Variant.Type" for v in e["values"]}
    by_plain_name = {k[len("TYPE_"):].replace("_", ""): v for k, v in type_ids.items()}

    def type_id(name):
        if name in ("Variant",):
            return "VARIANT_TYPE_ANY"
        if name.startswith("enum::") or name.startswith("bitfield::"):
            return type_ids["TYPE_INT"]
        if name.startswith("typedarray::"):
            return type_ids["TYPE_ARRAY"]
        if name.startswith("typeddictionary::"):
            return type_ids["TYPE_DICTIONARY"]
        if name in classes:
            return type_ids["TYPE_OBJECT"]
        # Variant.Type names without underscores: TYPE_PACKED_FLOAT32_ARRAY → PACKEDFLOAT32ARRAY
        key = name.upper()
        return by_plain_name.get(key, "VARIANT_TYPE_UNSUPPORTED")

    mrows = []
    for b in api["builtin_classes"]:
        for m in b.get("methods", []):
            args = [a["type"] for a in m.get("arguments", [])]
            flags = []
            if m.get("is_vararg"):
                flags.append("BM_VARARG")
            if m.get("is_static"):
                flags.append("BM_STATIC")
            if len(args) > 8 or any(a.get("default_value") is not None for a in m.get("arguments", [])):
                flags.append("BM_DEFAULTS")
            ret = m.get("return_type", "void")
            ret_id = "VARIANT_TYPE_VOID" if ret == "void" else type_id(ret)
            arg_ids = ", ".join(str(type_id(a)) for a in args[:8]) or "0"
            mrows.append((b["name"], m["name"], m["hash"], ret_id, len(args), arg_ids, " | ".join(flags) or "0"))
    mrows.sort()
    with open(os.path.join(out_dir, "builtin_method_data.inc"), "w") as out:
        out.write("// Generated by tools/gen_api_data.py; do not edit.\n")
        for r in mrows:
            out.write(f'{{"{r[0]}", "{r[1]}", {r[2]}LL, {r[3]}, {r[4]}, {{{r[5]}}}, {r[6]}}},\n')
    rows = builtin_rows
    with open(os.path.join(out_dir, "builtin_data.inc"), "w") as out:
        out.write("// Generated by tools/gen_api_data.py; do not edit.\n")
        for r in rows:
            out.write(f'{{"{r[0]}", "{r[1]}", {r[2]}, {r[3]}LL}},\n')


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
